### ISSUE TITLE
Start not work for me!

### ISSUE THREAD

**Issue by krokogames** [phoomin2012/travian-kingdom#1]
hi i tested your project but i need your help install this project

my problem : http://imgur.com/YRcEQBT

thx for help :)

WORKS I HAVE BAD xampp need reinstall (y)

**Comment by phoomin2012** [comment]
Sorry, about less installation document. If you use in localhost, you should edit hosts file to use some domain and edit apache config. In default config, I use t5th.ph domain for tested.
This is my hosts file
```
# Travian Kingdom
127.0.0.1       t5th.ph
127.0.0.1       kingdoms.t5th.ph
127.0.0.1       kingdom.t5th.ph
127.0.0.1       mellon.t5th.ph
127.0.0.1       lobby.t5th.ph
127.0.0.1       cdn.t5th.ph
127.0.0.1       ks1.t5th.ph
127.0.0.1       ks2.t5th.ph
127.0.0.1       ks3.t5th.ph
```
