### ISSUE TITLE
Where do you wish to found your village?

### ISSUE THREAD

**Issue by michaelabrahantes** [phoomin2012/travian-kingdom#13]
I click on found village and nothing happens in any position lets me create the village ?

**Comment by phoomin2012** [comment]
Do you use last version?

**Comment by michaelabrahantes** [comment]
yes already update and tested i don`t know what i`m doing wrong :(

**Comment by phoomin2012** [comment]
check that client to node or not

**Comment by michaelabrahantes** [comment]
if i had to constantly reload the page that means no connect to node ?

**Comment by phoomin2012** [comment]
Yes

Please give more details about error or screenshot

**Comment by michaelabrahantes** [comment]
i fixed my node and i reinstall all again now everything works but i still have problem whit found my village 
nothing happend after i click on the button where do i have to look for give you more info ?
![stuck](https://user-images.githubusercontent.com/25045386/30090668-f3fbd80c-9282-11e7-9a74-0926f53699be.jpg)
log php
![log](https://user-images.githubusercontent.com/25045386/30094032-588302d2-9297-11e7-85ac-cb7e0be7db4a.jpg)

**Comment by phoomin2012** [comment]
You use old database. Please upgrade to new version. You can use admin panel for easy install

**Comment by michaelabrahantes** [comment]
How do I open the admin panel ?

**Comment by phoomin2012** [comment]
Go to admin folder

**Comment by michaelabrahantes** [comment]
I had to call him by ip thanks
