### ISSUE TITLE
does it can work on a windows server?

### ISSUE THREAD

**Issue by lotu5david** [phoomin2012/travian-kingdom#15]
i configed the vhosts .but it also can not be work.i use a win server 2008 & xampp 3.2.2
my domin is 2stars.cc  when i visit the web site .it redirect to the address:
kingdoms.2stars.cc
but it can display nothing .
my vhost file like this:

<VirtualHost *:80>
    # Index
    ServerAdmin 2stars.cc
    ServerName  2stars.cc
    DocumentRoot "C:/xampp/htdocs/travian5"
    ErrorLog "logs/t5.ph-error_log"
    CustomLog "logs/t5.ph-access_log" common
</VirtualHost>
<VirtualHost *:80>
    # Index
    ServerAdmin kingdoms.2stars.cc
    ServerName kingdoms.2stars.cc
    DocumentRoot "C:/xampp/htdocs/travian5/index"
    ErrorLog "logs/kingdoms.t5.ph-error_log"
    CustomLog "logs/kingdoms.t5.ph-access_log" common
</VirtualHost>
<VirtualHost *:80>
    # Mellon service (Account service)
    ServerAdmin mellon.2stars.cc
    ServerName mellon.2stars.cc
    DocumentRoot "C:/xampp/htdocs/travian5/mellon"
    ErrorLog "logs/mellon.t5.ph-error_log"
    CustomLog "logs/mellon.t5.ph-access_log" common
    Header set Access-Control-Allow-Origin "*"

    AllowEncodedSlashes on
</VirtualHost>
<VirtualHost *:80>
    # CDN
    ServerAdmin cdn.2stars.cc
    ServerName cdn.2stars.cc
    DocumentRoot "C:/xampp/htdocs/travian5/cdn"
    ErrorLog "logs/cdn.t5th.ph-error_log"
    CustomLog "logs/cdn.t5th.ph-access_log" common
    Header set Access-Control-Allow-Origin "*"
</VirtualHost>
<VirtualHost *:80>
    # Lobby
    ServerAdmin lobby.2stars.cc
    ServerName lobby.2stars.cc
    DocumentRoot "C:/xampp/htdocs/travian5/lobby"
    ErrorLog "logs/lobby.t5.ph-error_log"
    CustomLog "logs/lobby.t5.ph-access_log" common
</VirtualHost>
<VirtualHost *:80>
    # Game
    ServerAdmin ks1.2stars.cc
    ServerName ks1.2stars.cc
    DocumentRoot "C:/xampp/htdocs/travian5/game/s1"
    ErrorLog "logs/ks1.t5.ph-error_log"
    CustomLog "logs/ks1.t5.ph-access_log" common
</VirtualHost>

can you give me some help?

**Comment by phoomin2012** [comment]
It alway redirect to subdomain kingdoms.XXXX.XX because it is home page.
I think you should send me screenshot of developer console to get more info about error.

**Comment by lotu5david** [comment]
[2stars.cc/1.jpg](url)

**Comment by lotu5david** [comment]
<img src ="http://www.2stars.cc/1.jpg">

**Comment by lotu5david** [comment]
when i use firefox it like the picture shows.
when i use chrome and opera it shows "DNS_PROBE_FINISHED_NXDOMAIN"

**Comment by lotu5david** [comment]
if i use address like 2stars.cc/travian5  without the vhost config. i get picture like this.
<img src = "http://2stars.cc/2.jpg"/>
<img src = "http://2stars.cc/3.jpg"/>

**Comment by lotu5david** [comment]
<img src = "http://2stars.cc/4.jpg"/>

**Comment by phoomin2012** [comment]
Problem from DNS config. You must config subdomain to point to your too.

**Comment by lotu5david** [comment]
you mean i should set subdomain  "kingdoms.2stars.cc" point to my domain "2stars.cc"?

**Comment by phoomin2012** [comment]
Yes, but point to you server ip

**Comment by lotu5david** [comment]
ok,tks.i will try .

**Comment by lotu5david** [comment]
<img src = "2stars.cc/7.jpg"/>
<img src = "2stars.cc/8.jpg"/>
i can login now .but when i login success i enter this step.when i click the gameserver the web redirect to the address http://ks1.t5.ph. 
can you help me?

**Comment by lotu5david** [comment]
i can enter the game now. thank you very much.
