### ISSUE TITLE
again dont connect with server ?

### ISSUE THREAD

**Issue by krokogames** [phoomin2012/travian-kingdom#2]
hi i setting my domain on my hosts file and setting config.php main page work but i click Start Game and Select Tribe button not work and not show my server name

Login same problem click login and stay only on loading animation.

picture: http://imgur.com/a/xrxeQ

console not write error only Ping mysql and next write send node.

**Comment by phoomin2012** [comment]
Now, not support to start game from index. You must to use login button and register before play.
You can see progress of this project from README file

**Comment by krokogames** [comment]
Well we just got it wrong I just set mysql db and config thank you for the help and I'm looking forward to it's going to be more hold of your thumbs.
