### ISSUE TITLE
the login is stuck at 50%

### ISSUE THREAD

**Issue by anasmsb** [phoomin2012/travian-kingdom#3]
I followed the installation step by step except for the hosts file and set domains I  just want to test it by localhost directory when I try to run the game\s1\index the loading is stuck at 50% 
I created new server API and setup the conf file and created the database and the data is saved in DB  
I started node and send node.. is in CMD no errors
![2017-08-01](https://user-images.githubusercontent.com/10762797/28839903-d4e99d00-76fd-11e7-991b-fcc63af0d228.png)
I created the host files and setup the urls but still the same 

<VirtualHost *:80>
	ServerName t5.k
	DocumentRoot "c:/wamp64/www/travian5"
	<Directory  "c:/wamp64/www/travian5/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>

<VirtualHost *:80>
	ServerName kingdoms.t5.k
	DocumentRoot "c:/wamp64/www/travian5/index"
	<Directory  "c:/wamp64/www/travian5/index/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>

<VirtualHost *:80>
	ServerName mellon.t5.k
	DocumentRoot "c:/wamp64/www/travian5/mellon"
	<Directory  "c:/wamp64/www/travian5/mellon/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>

<VirtualHost *:80>
	ServerName cdn.t5.k
	DocumentRoot "c:/wamp64/www/travian5/cdn"
	<Directory  "c:/wamp64/www/travian5/cdn/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>

<VirtualHost *:80>
	ServerName lobby.t5.k
	DocumentRoot "c:/wamp64/www/travian5/lobby"
	<Directory  "c:/wamp64/www/travian5/lobby/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>

<VirtualHost *:80>
	ServerName ks1.t5.k
	DocumentRoot "c:/wamp64/www/travian5/game/s1"
	<Directory  "c:/wamp64/www/travian5/game/s1/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>
 

the host file is 
127.0.0.1	t5.k
::1	t5.k

127.0.0.1	kingdoms.t5.k
::1	kingdoms.t5.k

127.0.0.1	mellon.t5.k
::1	mellon.t5.k

127.0.0.1	cdn.t5.k
::1	cdn.t5.k

127.0.0.1	lobby.t5.k
::1	lobby.t5.k

127.0.0.1	ks1.t5.k
::1	ks1.t5.k

I find out that the background is covering this error 
( ! ) Notice: Undefined index: s1_uid in C:\wamp64\www\travian5\game\s1\engine\village.php on line 134 
Call Stack 
# Time Memory Function Location 
1 0.0020 431216 {main}( ) ...\index.php:0 
2 0.0030 480376 include_once( 'C:\wamp64\www\travian5\game\s1\engine\engine.php' ) ...\index.php:2 
3 0.0850 5814472 Village->LoadData( ) ...\engine.php:93 

0% LoadingScreen.Action.Logout 
LOADING
phoomin009 on Developing 

--------------------------------------------------------------------------------

LoadingScreen.Action.Logout.RandomText 
Building Wonders of the World 

thanks for help

**Comment by krokogames** [comment]
check index/engine/config.php

and start with url yourdomain.tk/index/ and click button login 

![obrazek](https://user-images.githubusercontent.com/7843239/28850104-e7f43a46-771a-11e7-9518-0d83ae21b863.png)

vhost my apache:

![obrazek](https://user-images.githubusercontent.com/7843239/28850161-3ea11efe-771b-11e7-9be1-957bcaf90d69.png)

and my hosts files 
# Travian Kondoms

127.0.0.1		krokian.kroko
127.0.0.1		kingdoms.krokian.kroko
127.0.0.1		kingdom.krokian.kroko
127.0.0.1		mellon.krokian.kroko
127.0.0.1		lobby.krokian.kroko
127.0.0.1		cdn.krokian.kroko
127.0.0.1		ks1.krokian.kroko

[localhost]

**Comment by phoomin2012** [comment]
Please check your database and file game\s1\engine\village.php on line 134

**Comment by phoomin2012** [comment]
I check code in error that you tell me. It said that session doesn’t exist.
Please check that you login correctly

**Comment by anasmsb** [comment]
![2017-08-02 1](https://user-images.githubusercontent.com/10762797/28878845-2e076fd8-77a9-11e7-91b9-8642b26fe583.png)
the login button does not work it clicked but does not give any respond

**Comment by phoomin2012** [comment]
I see. I think something wrong in your config. I think link to cdn (assets file css,js) broken.

**Comment by phoomin2012** [comment]
This script can’t use localhost to access. You should to use to create fake domain and subdomain (I see you do it) and subdomain that you create should point at each of directory. Not point at project directory.

**Comment by anasmsb** [comment]
this is the link to and subdomain should point at (each of directory )
I did not get what you meant by that 
this the domains and there points 


# Virtual Hosts
#

<VirtualHost *:80>
	ServerName localhost
	DocumentRoot c:/wamp64/www
	<Directory  "c:/wamp64/www/">
        Options +Indexes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted
	</Directory>
</VirtualHost>

#

<VirtualHost *:80>
	ServerName t5.k
	DocumentRoot "c:/wamp64/www/travian5"
	<Directory  "c:/wamp64/www/travian5/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>


<VirtualHost *:80>
	ServerName kingdoms.t5.k
	DocumentRoot "c:/wamp64/www/travian5/index"
	<Directory  "c:/wamp64/www/travian5/index/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>


<VirtualHost *:80>
	ServerName mellon.t5.k
	DocumentRoot "c:/wamp64/www/travian5/mellon"
	<Directory  "c:/wamp64/www/travian5/mellon/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>


<VirtualHost *:80>
	ServerName cdn.t5.k
	DocumentRoot "c:/wamp64/www/travian5/cdn"
	<Directory  "c:/wamp64/www/travian5/cdn/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>


<VirtualHost *:80>
	ServerName lobby.t5.k
	DocumentRoot "c:/wamp64/www/travian5/lobby"
	<Directory  "c:/wamp64/www/travian5/lobby/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>


<VirtualHost *:80>
	ServerName ks1.t5.k
	DocumentRoot "c:/wamp64/www/travian5/game/s1"
	<Directory  "c:/wamp64/www/travian5/game/s1/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>

**Comment by anasmsb** [comment]
I well install xampp and try to set it up by the settings that you provide and give it try and then come back to you if something go wrong

**Comment by anasmsb** [comment]
Ok I find out that when I used wamp that wamp has Different setting and here is what was wrong 
![2017-08-02 3](https://user-images.githubusercontent.com/10762797/28891695-15d962f6-77d4-11e7-95c8-475e4abe804f.png)

and then 
![2017-08-02 4](https://user-images.githubusercontent.com/10762797/28891704-1ee09734-77d4-11e7-8a99-7edd824c5307.png)
this is what was wrong in wamp setting now I also have another problem in setting domains in config.php you must edit it to your domains 
![2017-08-02 5](https://user-images.githubusercontent.com/10762797/28891763-499f006e-77d4-11e7-8a81-56daeb1e6c9d.png)

And that is all 
I did not try to change to xampp because I did't not use it before......




now I have this problem when I hit log in 
![2017-08-02 6](https://user-images.githubusercontent.com/10762797/28891843-858f6d98-77d4-11e7-9640-0eeee458b147.png)

I well try to find out what is wrong with it and report back if somthing new come out and if someone know why help is appreciated 

sorry for bad English
thanks

**Comment by anasmsb** [comment]
as for the login problem 
there is something wrong with this function the execute command to be more specific what is it how to fix it I don't know this is the first time I see this method in executing mysql commands and web programming is not my strength .

the File path is mellon\engine\essentials.php

function query($sql,$array=array()){
    global $engine;
    $q = $engine->sql->prepare($sql);
    $q->execute($array);
    //$engine->error->sql =  $engine->sql->errorInfo();
    return $q;
}

I hope I Helped with such info.

**Comment by phoomin2012** [comment]
Use new version please, I add error handle that will add error to mysql. So, very easy to see error

**Comment by phoomin2012** [comment]
In config, there have two config because one is localhost config and one is other host config.

**Comment by phoomin2012** [comment]
In images that you give, I think have something wrong with mellon service.

**Comment by krokogames** [comment]
me work fine 

![obrazek](https://user-images.githubusercontent.com/7843239/28907249-649df50c-781d-11e7-879a-cb9c98a767b5.png)

![obrazek](https://user-images.githubusercontent.com/7843239/28907277-9a1f138c-781d-11e7-9637-28e4b7961077.png)

![obrazek](https://user-images.githubusercontent.com/7843239/28907315-d889ca40-781d-11e7-94fd-f57a609ba35b.png)


db log: 

![obrazek](https://user-images.githubusercontent.com/7843239/28907331-ea5622e6-781d-11e7-9a2c-f0826508b79b.png)

**Comment by anasmsb** [comment]
I am using the new version and it does not record any bug due to the error in the execute method I well do more research  and see what comes.

**Comment by phoomin2012** [comment]
Thanks for your interest. I hope that all of you will help together to improve this script.

**Comment by mosessaleh** [comment]
Hi all
Can I get a copy of your works?
I want to join the project with you.

Thanx
