### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by JoNMii** [phoomin2012/travian-kingdom#6]
Hi, 

I managed to install all and i got working but all timers when they got to 0 i forced to restart to get all updated stuff.

i have 2 node servers listening and php.exe runing every second....

What's the problem?

**Comment by lotu5david** [comment]
i also met the same problems.

**Comment by lotu5david** [comment]
can not load the server. and can not login.

**Comment by JoNMii** [comment]
It was because client is not connected to node. Personal issue. Not bug.
