### ISSUE TITLE
Barrack quest only completed if is positionated

### ISSUE THREAD

**Issue by JoNMii** [phoomin2012/travian-kingdom#7]
Cant finish quest.
![image](https://user-images.githubusercontent.com/395430/30010370-895bfb70-912f-11e7-91b8-0925e99d2f64.png)

**Comment by phoomin2012** [comment]
Game was fix position of barrack. Quest will only continue when build barrack finish.

**Comment by JoNMii** [comment]
Testing right now, in official game I guess that it only can be placed on this site.

**Comment by phoomin2012** [comment]
Yes
