### ISSUE TITLE
CPU ussage from apache2 and PHP

### ISSUE THREAD

**Issue by JoNMii** [phoomin2012/travian-kingdom#9]
I have a i7 and 24gb of ram.
![image](https://user-images.githubusercontent.com/395430/30063505-38aaa5f2-924f-11e7-8e9b-997750cde3a3.png)

Apache2 lag starts when is click on Found village, then even a F5 doesnt load until apache2 restart.

**Comment by phoomin2012** [comment]
PHP process usually use leak cpu but problem when found village I think because of socket send wrong data to client.

**Comment by phoomin2012** [comment]
Fixed it
